### ISSUE TITLE
Can't find the register keys

### ISSUE THREAD

**Issue by rruiter87** [dfreiberger/twincat-high-dpi-fix#1] opened 2022-06-30 06:06 UTC
For me 
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TcXaeShell.exe`
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\devenv.exe`
do not exist. I also searched for other `devenv.exe` entries or for `Image File Execution Options` at other locations. None of them contain a `dpiAweness` entry.

**Comment by dfreiberger** [comment] 2022-06-30 15:15
Which Windows OS are you on, and which version of TwinCAT are you using? Maybe I can try to reproduce the issue.

Also: for me the key's didn't exist by default either, I needed to create them. I believe clicking on the .reg file in this repository should create the key, but you can also do it manually. Make sure to restart Visual Studio after.

There is also an article here which proposes some alternate ways to fix the issue: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2017/designers/disable-dpi-awareness?view=vs-2017

**Comment by rruiter87** [comment] 2022-07-01 07:17
Manually adding the `devenv.exe/dpiAwareness` entry worked! Visual Studio is pixelated 👍. Running the script didn't work for me. I'm guessing because I didn't run it as admin.

![image](https://user-images.githubusercontent.com/98890535/176844686-278247c8-49dd-472e-886e-6d6137c6ba29.png)


- Microsoft Windows 10 Education 10.0.19043 Build 19043
- TwinCAT 3.1.4024.29
- Microsoft Visual Studio Community 2019 Version 16.11.13

**Comment by dfreiberger** [comment] 2022-08-20 20:23
Closing as it looks like this worked for you.

**Closed as completed by dfreiberger** 2022-08-20 20:23 UTC
